### ISSUE TITLE
Issue 1: User can see their car.

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Generate an layout class with HTML and CSS
  - [x] Bound width 100% and height 100vh
  - [x] Bound should have position as relative
- [x] Add another div to wrap the image tag for the car (act as a hitbox for the car)
- [x] the div have position absolute
- [x] Have a data object to hold information of the car
  - [x] have a current facing property
  - [x] have a current position property
- [x] car start facing to the right at top left corner
- [x] Clean up any errors
- [x] Clean up any unnecessary CSS and HTML.
