### ISSUE TITLE
Issue 2: User can turn their car.

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] User can turn their car by pressing the arrows keys on their keyboard.
  - [x] add an event listener to the Bound div
  - [x] check if the key press is either the right or left arrow
  - [x] if the key is not an arrow. do nothing
  - [x] Uses the current facing property on the car object to calculate the next orientation of the car
    - [x] if the key if left arrow turn the car -90 degree
    - [x] if they key is right arrow turn the car 90 degree
    - [x] set the new direction as current facing property on the car object
    - [x] Use transition in css to make the car look like a normal turn
- [x] Clean up any errors
- [x] Clean up any unnecessary CSS and HTML
