### ISSUE TITLE
Issue 3: User can start their car:

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x]  Add the handle keypress event to filter in space bar presses
- [x] Add an isMoving property to the car object
  - [x] default it to false
  - [x] when the spacebar is pressed change it to true
- [x]  Using the car.facing properties determine which direction the car is facing
  - [x] queryselect for the hitbox div
  - [x] use div.styles to move the div 5px per press in the right direction
  - [x] uses the position properties of the car object to determine where the car is currently at
    - [x]  after doing calculation of where the car need to put the new position in as current position
  - [x] let the car move off screen
- [x] Fix any and all errors
- [x] clean up unnessary CSS and HTML
